apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mae-demo
  namespace: mae
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: mae-demo
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_repository
    value: ssh://git@github.com/maelarge/config-mae-demo.git
  - name: gitops_branch
    value: main
  source:
    git:
      url: https://github.com/maelarge/mae-demo
      ref:
        branch: main
